### PR TITLE
Feature laurence

### PR DESCRIPTION
**Pull request by lau-lm**
I add two text line in the footer.

### CODE REVIEW

**Comment by lau-lm** [comment]
@Turmorofall @zoemhart @laurianecollet What do you think about my amazing changes ?

**Comment by Turmorofall** [comment]
I don't validate that, this is bad really bad. SHAME !!! SHAME !!!! @hy-lau

**Comment by lau-lm** [comment]
Thank you @Turmorofall for your constructive comment. Maybe you can be more explicit ?

**Comment by z888e** [comment]
this is amazing! amazing

**Pull request merged**
